package com.abcyb101.notetakerprojectv2.controllers;

import java.util.List;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/v1/helloworld")
public class DevController {

	@GetMapping
	public ResponseEntity<String> sayHello() {
		return ResponseEntity.ok("Hello, I'm the API");
	}
	
	@GetMapping("/json-list-greeting")
	public List<String> sayHelloAsJsonList() {
		return List.of("Hello","I'm the API");
	}
	
	@GetMapping("/say-bye")
	public ResponseEntity<String> sayGoodbye() {
		return ResponseEntity.ok("bye");
	}
	
	/*
	 * To test this, when the security customization has not yet been implemented:
	 * Postman GET  @ http://localhost:8089/api/v1/helloworld
	 * Authorization header type: Basic Auth
	 * Username: user
	 * Password: as generated by Spring on startup.
	 */

}

